/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "blog": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
